// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = -1005; // obj_Global
global.__objectDepths[1] = -1002; // obj_Tooltip
global.__objectDepths[2] = 0; // obj_MovePlayer
global.__objectDepths[3] = 0; // obj_AllEnemyParent
global.__objectDepths[4] = 0; // obj_BasicMeleeEnemyParent
global.__objectDepths[5] = 0; // obj_Fallen
global.__objectDepths[6] = 0; // obj_BasicMeleeChampionParent
global.__objectDepths[7] = 0; // obj_FallenShaman
global.__objectDepths[8] = 0; // obj_BossParent
global.__objectDepths[9] = 0; // obj_Diablo
global.__objectDepths[10] = 0; // obj_GroundItemParent
global.__objectDepths[11] = 0; // obj_HeadParent
global.__objectDepths[12] = 0; // obj_Cap
global.__objectDepths[13] = 0; // obj_BodyParent
global.__objectDepths[14] = 0; // obj_LeatherArmor
global.__objectDepths[15] = 0; // obj_OffHandParent
global.__objectDepths[16] = 0; // obj_Buckler
global.__objectDepths[17] = 0; // obj_GlovesParent
global.__objectDepths[18] = 0; // obj_LeatherGloves
global.__objectDepths[19] = 0; // obj_BeltParent
global.__objectDepths[20] = 0; // obj_LeatherBelt
global.__objectDepths[21] = 0; // obj_BootsParent
global.__objectDepths[22] = 0; // obj_LeatherBoots
global.__objectDepths[23] = 0; // obj_AmuletParent
global.__objectDepths[24] = 0; // obj_Amulet
global.__objectDepths[25] = 0; // obj_RingParent
global.__objectDepths[26] = 0; // obj_Ring
global.__objectDepths[27] = 0; // obj_MiscParent
global.__objectDepths[28] = 0; // obj_BookIdentify
global.__objectDepths[29] = 0; // obj_BookPortal
global.__objectDepths[30] = 0; // obj_MinorHealthPotion
global.__objectDepths[31] = 0; // obj_MinorManaPotion
global.__objectDepths[32] = 0; // obj_RejuvinationPotion
global.__objectDepths[33] = 0; // obj_SkeletonKey
global.__objectDepths[34] = 0; // obj_WeaponParent
global.__objectDepths[35] = 0; // obj_ShortSword
global.__objectDepths[36] = 0; // obj_SelectClassArcher
global.__objectDepths[37] = 0; // obj_SelectClassMage
global.__objectDepths[38] = 0; // obj_SelectClassWarrior
global.__objectDepths[39] = 0; // obj_PlayerGenerator
global.__objectDepths[40] = -1000; // obj_Inventory
global.__objectDepths[41] = -1001; // obj_InventoryButton
global.__objectDepths[42] = -1001; // obj_EquipButtonParent
global.__objectDepths[43] = -501; // obj_BeltButton
global.__objectDepths[44] = -1001; // obj_EquipHead
global.__objectDepths[45] = -1001; // obj_EquipWeapon
global.__objectDepths[46] = -1001; // obj_EquipChest
global.__objectDepths[47] = -1001; // obj_EquipOffhand
global.__objectDepths[48] = -1001; // obj_EquipGloves
global.__objectDepths[49] = -1001; // obj_EquipBelt
global.__objectDepths[50] = -1001; // obj_EquipRing1
global.__objectDepths[51] = -1001; // obj_EquipAmulet
global.__objectDepths[52] = -1001; // obj_EquipRing2
global.__objectDepths[53] = -1001; // obj_EquipBoots
global.__objectDepths[54] = -1002; // obj_Spellbook
global.__objectDepths[55] = -1002; // obj_Spellbook2
global.__objectDepths[56] = -1003; // obj_SpellbookFirebolt
global.__objectDepths[57] = -1003; // obj_SpellbookIcebolt
global.__objectDepths[58] = -1000; // obj_StatsMenu
global.__objectDepths[59] = -1001; // obj_IncreaseStrength
global.__objectDepths[60] = -1001; // obj_IncreaseDexterity
global.__objectDepths[61] = -1001; // obj_IncreaseVitality
global.__objectDepths[62] = -1001; // obj_IncreaseEnergy
global.__objectDepths[63] = -500; // obj_UI
global.__objectDepths[64] = -501; // obj_StatUpButton
global.__objectDepths[65] = -501; // obj_InventoryButtonUI
global.__objectDepths[66] = -501; // obj_SkillTreeButtonUI
global.__objectDepths[67] = -501; // obj_Skill1Button
global.__objectDepths[68] = -501; // obj_Skill2Button
global.__objectDepths[69] = 0; // obj_PlayerController
global.__objectDepths[70] = 0; // obj_PlayerParent
global.__objectDepths[71] = -1; // obj_Archer
global.__objectDepths[72] = -1; // obj_Mage
global.__objectDepths[73] = -1; // obj_Warrior
global.__objectDepths[74] = -2; // obj_OffensiveSpellParent
global.__objectDepths[75] = -2; // obj_SpellFirebolt
global.__objectDepths[76] = -2; // obj_SpellIcebolt
global.__objectDepths[77] = 0; // obj_BookFirebolt
global.__objectDepths[78] = 0; // obj_BookIcebolt


global.__objectNames[0] = "obj_Global";
global.__objectNames[1] = "obj_Tooltip";
global.__objectNames[2] = "obj_MovePlayer";
global.__objectNames[3] = "obj_AllEnemyParent";
global.__objectNames[4] = "obj_BasicMeleeEnemyParent";
global.__objectNames[5] = "obj_Fallen";
global.__objectNames[6] = "obj_BasicMeleeChampionParent";
global.__objectNames[7] = "obj_FallenShaman";
global.__objectNames[8] = "obj_BossParent";
global.__objectNames[9] = "obj_Diablo";
global.__objectNames[10] = "obj_GroundItemParent";
global.__objectNames[11] = "obj_HeadParent";
global.__objectNames[12] = "obj_Cap";
global.__objectNames[13] = "obj_BodyParent";
global.__objectNames[14] = "obj_LeatherArmor";
global.__objectNames[15] = "obj_OffHandParent";
global.__objectNames[16] = "obj_Buckler";
global.__objectNames[17] = "obj_GlovesParent";
global.__objectNames[18] = "obj_LeatherGloves";
global.__objectNames[19] = "obj_BeltParent";
global.__objectNames[20] = "obj_LeatherBelt";
global.__objectNames[21] = "obj_BootsParent";
global.__objectNames[22] = "obj_LeatherBoots";
global.__objectNames[23] = "obj_AmuletParent";
global.__objectNames[24] = "obj_Amulet";
global.__objectNames[25] = "obj_RingParent";
global.__objectNames[26] = "obj_Ring";
global.__objectNames[27] = "obj_MiscParent";
global.__objectNames[28] = "obj_BookIdentify";
global.__objectNames[29] = "obj_BookPortal";
global.__objectNames[30] = "obj_MinorHealthPotion";
global.__objectNames[31] = "obj_MinorManaPotion";
global.__objectNames[32] = "obj_RejuvinationPotion";
global.__objectNames[33] = "obj_SkeletonKey";
global.__objectNames[34] = "obj_WeaponParent";
global.__objectNames[35] = "obj_ShortSword";
global.__objectNames[36] = "obj_SelectClassArcher";
global.__objectNames[37] = "obj_SelectClassMage";
global.__objectNames[38] = "obj_SelectClassWarrior";
global.__objectNames[39] = "obj_PlayerGenerator";
global.__objectNames[40] = "obj_Inventory";
global.__objectNames[41] = "obj_InventoryButton";
global.__objectNames[42] = "obj_EquipButtonParent";
global.__objectNames[43] = "obj_BeltButton";
global.__objectNames[44] = "obj_EquipHead";
global.__objectNames[45] = "obj_EquipWeapon";
global.__objectNames[46] = "obj_EquipChest";
global.__objectNames[47] = "obj_EquipOffhand";
global.__objectNames[48] = "obj_EquipGloves";
global.__objectNames[49] = "obj_EquipBelt";
global.__objectNames[50] = "obj_EquipRing1";
global.__objectNames[51] = "obj_EquipAmulet";
global.__objectNames[52] = "obj_EquipRing2";
global.__objectNames[53] = "obj_EquipBoots";
global.__objectNames[54] = "obj_Spellbook";
global.__objectNames[55] = "obj_Spellbook2";
global.__objectNames[56] = "obj_SpellbookFirebolt";
global.__objectNames[57] = "obj_SpellbookIcebolt";
global.__objectNames[58] = "obj_StatsMenu";
global.__objectNames[59] = "obj_IncreaseStrength";
global.__objectNames[60] = "obj_IncreaseDexterity";
global.__objectNames[61] = "obj_IncreaseVitality";
global.__objectNames[62] = "obj_IncreaseEnergy";
global.__objectNames[63] = "obj_UI";
global.__objectNames[64] = "obj_StatUpButton";
global.__objectNames[65] = "obj_InventoryButtonUI";
global.__objectNames[66] = "obj_SkillTreeButtonUI";
global.__objectNames[67] = "obj_Skill1Button";
global.__objectNames[68] = "obj_Skill2Button";
global.__objectNames[69] = "obj_PlayerController";
global.__objectNames[70] = "obj_PlayerParent";
global.__objectNames[71] = "obj_Archer";
global.__objectNames[72] = "obj_Mage";
global.__objectNames[73] = "obj_Warrior";
global.__objectNames[74] = "obj_OffensiveSpellParent";
global.__objectNames[75] = "obj_SpellFirebolt";
global.__objectNames[76] = "obj_SpellIcebolt";
global.__objectNames[77] = "obj_BookFirebolt";
global.__objectNames[78] = "obj_BookIcebolt";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for